- hosts: test_runners
  user: "{{ client_user }}"

  vars_files:
    - vars/main.yml  

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: install the locales package
    apt: pkg=locales state=present

  - name: ensure the en_US locale exists
    locale_gen: name=en_US.UTF-8 state=present

  - name: set the locale
    command: /usr/sbin/update-locale LANG=en_US.UTF-8 --reset

  - name: Installing repo for Java 8 in Ubuntu
    become: true
    apt_repository: 
      repo: 'ppa:openjdk-r/ppa'
      state: present

  - name: ensure packages are installed
    apt: name={{ item }}
    with_items:
        - make
        - build-essential
        - git
        - python3
        - python3-pip

  - name: Install Python's selenium package
    command: pip3 install selenium

  - name: Install Python's fabric package
    command: pip3 install fabric

  - name: Install Python's Sendgrid package
    command: pip3 install sendgrid

  - name: Install Python's Twilio package
    command: pip3 install twilio

  - name: Create user that will run the tests
    user:
      name: testrunner
      shell: /bin/bash

  - name: Add Sendgrid API key environment variable
    lineinfile: dest=/home/testrunner/.bashrc line="export SENDGRID_API_KEY={{ sendgrid_api_key }}" insertafter='EOF'

  - name: Add Twilio account SID environment variable
    lineinfile: dest=/home/testrunner/.bashrc line="export TWILIO_ACCOUNT_SID={{ twilio_account_sid }}" insertafter='EOF'

  - name: Add Twilio auth token environment variable
    lineinfile: dest=/home/testrunner/.bashrc line="export TWILIO_AUTH_TOKEN={{ twilio_auth_token }}" insertafter='EOF'

  - name: Add Twilio phone number environment variable
    lineinfile: dest=/home/testrunner/.bashrc line="export TWILIO_PHONE_NUMBER={{ twilio_phone_number }}" insertafter='EOF'

  - name: Add list of emails to be notified
    lineinfile: dest=/home/testrunner/.bashrc line="export SEND_EMAIL_NOTIFICATIONS_TO={{ send_email_notifications_to }}" insertafter='EOF'

  - name: Add list of phone numbers to be notified
    lineinfile: dest=/home/testrunner/.bashrc line="export SEND_SMS_NOTIFICATIONS_TO={{ send_sms_notifications_to }}" insertafter='EOF'

  - name: Uploading the test files
    synchronize:
      src: tests
      dest: /home/testrunner/{{ project_name }}

  - name: Create cronjob for running the tests
    cron:
      minute: "*/30"
      user: testrunner
      job: "python3 /home/testrunner/{{ project_name }}/runner.py"

- hosts: test_runners
  user: "{{ client_user }}"

  vars_files:
    - vars/main.yml  

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk    
    - selenium