- hosts: test_runners
  user: "{{ client_user }}"

  vars_files:
    - vars/main.yml  

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: install the locales package
    apt: pkg=locales state=present

  - name: ensure the en_US locale exists
    locale_gen: name=en_US.UTF-8 state=present

  - name: set the locale
    command: /usr/sbin/update-locale LANG=en_US.UTF-8 --reset

  - name: Installing repo for Java 8 in Ubuntu
    become: true
    apt_repository: 
      repo: 'ppa:openjdk-r/ppa'
      state: present

  - name: ensure packages are installed
    apt: name={{ item }}
    with_items:
        - make
        - build-essential
        - git
        - python3
        - python3-pip

  - name: Install Python's selenium package
    command: pip3 install selenium

  - name: Create user that will run the tests
    user:
      name: testrunner
      shell: /bin/bash

- hosts: test_runners
  user: "{{ client_user }}"

  vars_files:
    - vars/main.yml  

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk    
    - selenium