- hosts: test_runners
  user: "{{ client_user }}"

  vars_files:
    - vars/main.yml  

  tasks:
  - name: Uploading the test files
    synchronize:
      src: tests
      dest: /home/testrunner/{{ project_name }}